config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'blogs#index'
  get 'blogs' => 'blogs#index'
  get   'blogs/new'  =>  'blogs#new'
  post  'blogs'      =>  'blogs#create'
  delete  'blogs/:id'  => 'blogs#destroy'
  get   'blogs/:id/edit'  => 'blogs#edit'
  patch   'blogs/:id'  => 'blogs#update'
  get   'users/:id'   =>  'users#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  before_action :move_to_index, except: :index

  def index
    @blogs =Blog.includes(:user).page(params[:page]).per(5).order("created_at DESC")
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.create( title: blog_params[:title], image: blog_params[:image], content: blog_params[:content], user_id: current_user.id)
  end

  def destroy
    @blog = Blog.find(params[:id])
    if @blog.user_id == current_user.id
      @blog.destroy
    end
  end

  def edit
    @blog = Blog.find(params[:id])
  end


  def update
    @blog = Blog.find(params[:id])
    if blog.user_id == current_user.id
      blog.update(blog_params)
    end
  end



  private
  def blog_params
    params.require(:blog).permit(:title, :image, :content)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end


 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @blogs = current_user.blogs.page(params[:page]).per(5).order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/create.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        投稿が完了しました。
      </h3>
      <a class="btn" href="/blogs">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/blogs/destroy.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/blogs/edit.html.erb
<%= form_for :blog, url: blogs_path do |f| %>
  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :image, "画像" %><br>
    <%= f.text_field :image %>
  </p>

  <p>
    <%= f.label :content, "内容" %><br>
    <%= f.text_area :content, cols: 60, rows: 20 %>
  </p>
 
  <p>
    <%= f.submit "修正"%>
  </p>
<% end %>

app/views/blogs/index.html.erb
<ul class="list_blog">
  <% @blogs.each do |blog| %>
   <% if user_signed_in? && current_user.id == blog.user_id %>
  <li>
    <h2><%= blog.title %></h2>
    <% if blog.image != "" %>
      <p><img src="<%= blog.image %>"></p>
    <% end %>
    <p><%= blog.content %></p>
    <p><%= blog.created_at %></p>
  </li>
 <% end %>


        <div class="more">
          <span><%= image_tag 'arrow_top.png' %></span>
          <ul class="more_list">
            <li>
              <%= link_to '編集', "/blogs/#{blog.id}/edit", method: :get %>
            </li>
            <li>
              <%= link_to '削除', "/blogs/#{blog.id}", method: :delete %>
            </li>
          </ul>
        </div>
      <% end %>
 


 <%= paginate(@blogs) %>
</ul> 

app/views/blogs/new.html.erb
<h1>新しい投稿</h1>
<%= form_for @blog, url: blogs_path do |f| %>
  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :image, "画像" %><br>
    <%= f.text_field :image %>
  </p>

  <p>
    <%= f.label :content, "内容" %><br>
    <%= f.text_area :content, cols: 60, rows: 20 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/blogs/update.html.erb
<div class="contents row">
    <div class="success">
      <h3>
        更新が完了しました。
      </h3>
      <a class="btn" href="/">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script type="text/javascript">
      WebFontConfig = {
        google: { families: [ 'Unica+One::latin' ] }
      };
      (function() {
        var wf = document.createElement('script');
        wf.src = ('https:' == document.location.protocol ? 'https' : 'http') +
          '://ajax.googleapis.com/ajax/libs/webfont/1/webfont.js';
        wf.type = 'text/javascript';
        wf.async = 'true';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(wf, s);
      })();
    </script>
  </head>

  <body>
    <header class="header">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">BLOG</a></h1>
         <% if user_signed_in? %>
         <div class="user_nav grid-6">
          
           <span><%= current_user.nickname %>
            <ul class="user__info">
              <li>
                <a href="/users/<%= current_user.id %>">マイページ</a>
          
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          
              </li>
            </ul>
          </span>
          
          
          <a class="post" href="/blogs/new">投稿する</a>
        </div>
        <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
        <% end %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <p>
        Copyright Blog 2019.
      </p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
 <div class="contents row" >
    <p><%= @nickname %>さんの投稿一覧</p>
    <% @blogs.each do |blog| %>
      <div class="content_post" style="background-image: url(<%= blog.image %>);">
        <%= simple_format(blog.content) %>
        <span class="title"><%= blog.title %></span>
      </div>
    <% end %>
    <%= paginate(@blogs) %>
  </div>